Repository Ordering-Inc/Ordering-UI, pull requests merged in 2020-11, with the labels that each got.

#144 improvements
  src/components/AddressDetails/index.js
  src/components/AddressDetails/styles.js
  src/components/AddressList/index.js
  src/components/AddressesPopover/index.js
  src/components/BusinessController/styles.js
  src/components/BusinessItemAccordion/styles.js
  src/components/BusinessProductsListing/index.js
  src/components/BusinessReviews/index.js
  src/components/BusinessReviews/styles.js
  src/components/Checkout/styles.js
  src/components/Cms/index.js
  src/components/FloatingButton/styles.js
  src/components/HomeHero/styles.js
  src/components/MyOrders/index.js
  src/components/ProductForm/styles.js
  src/components/ProductItemAccordion/styles.js
  src/components/ProductShare/styles.js
  src/components/SidebarMenu/styles.js
  src/components/SignUpForm/index.js
  src/components/UpsellingPage/styles.js
  src/components/UserProfileForm/index.js
  src/components/UserProfileForm/styles.js
  src/styles/Buttons/index.js
  src/styles/Selects/index.js
  template/Pages/Home/index.js
Labels: WIP

#153 Adapt some components for new ordering components
  src/components/LoginForm/index.js
  src/components/ProductForm/index.js
  src/components/SignUpForm/index.js
  template/app.js
Labels: enhancement

#157 Change design mobile and desktop, change delivery asset
  template/Pages/Home/styles.js
  template/assets/delivery-icon.svg
Labels: RC
