Repository Ordering-Inc/Ordering-UI, pull requests merged in 2020-10, with the labels that each got.

#44 [FIX] loginForm responsive issues
  src/components/LoginForm/index.js
  src/components/LoginForm/styles.js
  template/components/Header/index.js
  template/router.js
Labels: WIP

#60 validation to show caret when product has comments
  src/components/ProductItemAccordion/index.js
  src/components/ProductItemAccordion/styles.js
Labels: RTM

#69 Add google maps map in address form
  src/components/AddressForm/index.js
  src/components/AddressForm/styles.js
  src/components/HomeHero/index.js
  src/components/Modal/styles.js
Labels: RTM

#70 Improve header margin
  template/components/Header/styles.js
Labels: RTM

#72 Redirect to checkout list when uuid doesn't exist
  src/components/Checkout/index.js
  template/Pages/Checkout/index.js
Labels: RTM

#71 Improve single product style when is sold out
  src/components/SingleProductCard/styles.js
Labels: RTM

#64 Profile responsive
  src/components/UserProfileForm/ProfileOptions/styles.js
  src/components/UserProfileForm/index.js
  src/components/UserProfileForm/styles.js
Labels: RTM

#59 Issue popover user
  src/components/CartPopover/index.js
  src/components/UserPopover/index.js
  template/components/Header/index.js
Labels: RTM

#68 Refactor Business Information code and improve design
  src/components/BusinessBasicInformation/index.js
  src/components/BusinessInformation/index.js
  src/components/BusinessInformation/styles.js
  src/components/BusinessReviews/index.js
  src/components/BusinessReviews/styles.js
  src/utils/index.js
Labels: RTM

#74 Responsive for spinner loader
  src/components/SpinnerLoader/styles.js
Labels: RTM

#67 Fix time of the messages
  src/components/Messages/index.js
Labels: RTM

#63 Login form new desing
  src/components/FacebookLogin/index.js
  src/components/LoginForm/index.js
  src/components/LoginForm/styles.js
  src/styles/Buttons/index.js
  template/assets/IconFacebook.svg
Labels: RTM

#62 [FIX] font of Slogan
  src/components/HomeHero/index.js
Labels: RTM

#76 Improve design for Business Information
  src/components/BusinessBasicInformation/index.js
  src/components/BusinessInformation/index.js
  src/components/BusinessInformation/styles.js
  src/components/Modal/index.js
Labels: RTM

#75 Refactor code and improve google maps image on My orders
  src/components/MyOrders/index.js
  src/components/MyOrders/styles.js
Labels: Need review

#78 Fix search
  src/components/BusinessProductsListing/index.js
  src/components/BusinessesListing/index.js
  src/components/SearchBar/index.js
  src/styles/Inputs/index.js
Labels: Need review

#80 [ADD] functional component to Cms
  src/components/Cms/index.js
  src/components/PageNotFound/index.js
  template/Pages/Cms/index.js
Labels: Need review

#81 Improve checkout list validations when cart has no products
  src/components/Cart/index.js
  src/components/Checkout/index.js
  src/components/Checkout/styles.js
  template/Pages/Checkout/index.js
Labels: Need review

#66 Edit product from cart or checkout
  package-lock.json
  src/components/AddressList/styles.js
  src/components/BusinessProductsListing/index.js
  src/components/BusinessesListing/index.js
  src/components/Cart/index.js
  src/components/Modal/styles.js
  src/components/ProductForm/index.js
  src/components/ProductForm/styles.js
  src/components/ProductItemAccordion/index.js
  src/components/ProductItemAccordion/styles.js
  src/components/ProductOptionSubOption/index.js
  src/components/ProductOptionSubOption/styles.js
  src/components/ProductShare/styles.js
Labels: WIP

#47 Issues footer
  template/components/Footer/index.js
  template/components/Footer/styles.js
Labels: Need review

#87 Improve scrollbar style
  template/router.js
Labels: Need review

#86 Product Form issues
  src/components/BusinessProductsListing/index.js
  template/Pages/BusinessProductsList/index.js
Labels: Need review

#85 Improve Cart design
  src/components/BusinessBasicInformation/index.js
  src/components/BusinessController/index.js
  src/components/BusinessInformation/index.js
  src/components/BusinessItemAccordion/index.js
  src/components/BusinessItemAccordion/styles.js
  src/components/Cart/index.js
  src/components/Cart/styles.js
  src/components/CartPopover/index.js
  src/components/CartPopover/styles.js
  src/components/Checkout/styles.js
  src/components/CouponControl/index.js
  src/components/CouponControl/styles.js
  src/components/OrderDetails/index.js
  src/components/PaymentOptions/styles.js
  src/components/ProductForm/index.js
  src/components/ProductForm/styles.js
  src/components/ProductItemAccordion/index.js
  src/components/ProductItemAccordion/styles.js
  src/components/ProductShare/styles.js
  src/contexts/ThemeContext/index.js
  src/utils/index.js
Labels: Need review

#91 [ADD] Order Types for addressForm and fix bug of select
  src/components/AddressList/index.js
  src/components/Modal/index.js
  src/components/Modal/styles.js
  src/components/OrderTypeSelectorHeader/index.js
Labels: Need review

#100 Address improvements and fixes
  src/components/AddressDetails/index.js
  src/components/AddressForm/index.js
  src/components/AddressForm/styles.js
  src/components/AddressList/index.js
  src/components/BusinessesListing/index.js
  src/components/Cart/index.js
  src/components/HomeHero/index.js
  src/components/ProductForm/index.js
  template/assets/location-marker.svg
Labels: Need review

#99 Checkout improvements
  src/components/BusinessItemAccordion/index.js
  src/components/Cart/index.js
  src/components/CartPopover/index.js
  src/components/Checkout/index.js
  template/router.js
Labels: Need review

#90 Open cart when user add product
  src/components/BusinessItemAccordion/index.js
  src/components/BusinessItemAccordion/styles.js
  src/components/ProductForm/index.js
  src/components/ProductItemAccordion/index.js
  src/components/ProductItemAccordion/styles.js
  template/components/Header/index.js
Labels: Need review

#101 Sign up / Login / Forgot password improvements
  src/components/AddressList/index.js
  src/components/AddressList/styles.js
  src/components/ForgotPasswordForm/index.js
  src/components/ForgotPasswordForm/styles.js
  src/components/LoginForm/index.js
  src/components/LoginForm/styles.js
  src/components/SignUpForm/index.js
  src/components/SignUpForm/styles.js
  template/router.js
Labels: Need review

#108 Redirect home from search route when user haven't address
  template/app.js
Labels: Need review

#114 Preload offline component
  src/components/NotNetworkConnectivity/index.js
  template/app.js
Labels: Need review

#109 Add background color to avoid transparent business information modal
  src/components/BusinessInformation/styles.js
Labels: Need review

#110 Open cart or business when user add product
  src/components/BusinessItemAccordion/index.js
Labels: Need review

#111 Revert style of sold out tag for products
  src/components/SingleProductCard/styles.js
Labels: Need review

#112 Add not image for products haven't image
  src/components/ProductForm/index.js
  src/components/ProductForm/styles.js
  src/components/SingleProductCard/index.js
  src/components/SingleProductCard/styles.js
  template/assets/not-image.png
Labels: Need review

#113 Add icon when user haven't photo
  src/components/Image/index.js
  src/components/OrderDetails/index.js
  src/components/OrderDetails/styles.js
  src/components/UserPopover/index.js
  src/components/UserPopover/styles.js
  src/components/UserProfileForm/index.js
  src/components/UserProfileForm/styles.js
Labels: Need review

#122 Align increment-decrement buttons in product form
  src/components/ProductForm/index.js
  src/components/ProductForm/styles.js
Labels: Need review

#124 Change text when business is closed
  src/components/Cart/index.js
Labels: Need review

#125 Checkout fixes
  src/components/AddressDetails/index.js
  src/components/AddressDetails/styles.js
  src/components/Checkout/index.js
  src/components/Checkout/styles.js
Labels: Need review

#121 Improve links to navigate login popup on product form
  src/components/ForgotPasswordForm/index.js
  src/components/ForgotPasswordForm/styles.js
  src/components/ProductForm/index.js
  src/components/SignUpForm/index.js
  src/components/SignUpForm/styles.js
Labels: Need review, with conflicts

#130 Change popovers to modals when width is less than 768px
  src/components/AddressContent/index.js
  src/components/AddressContent/styles.js
  src/components/AddressForm/styles.js
  src/components/AddressesPopover/index.js
  src/components/Cart/index.js
  src/components/CartContent/index.js
  src/components/CartContent/styles.js
  src/components/CartPopover/index.js
  src/components/CartPopover/styles.js
  src/components/Header/index.js
  src/components/Header/styles.js
  src/components/HeaderOption/index.js
  src/components/HeaderOption/styles.js
  src/components/Modal/styles.js
  src/components/MomentContent/index.js
  src/components/MomentContent/styles.js
  src/components/MomentControl/index.js
  src/components/MomentControl/styles.js
  src/components/MomentPopover/index.js
  src/components/ProductItemAccordion/styles.js
Labels: Need review

#139 Sidebar menu
  src/components/Header/index.js
  src/components/Header/styles.js
  src/components/LogoutButton/index.js
  src/components/SidebarMenu/index.js
  src/components/SidebarMenu/styles.js
Labels: enhancement
